### ISSUE TITLE
How to add new resolution ?

### ISSUE THREAD

**Issue by openelearning** [avafinger/opi-win-a64-firmware#1]
Hello,

Thanks a lot for this cool work. You have helped 2 user to make their OPIwin working ( cf. http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=2931&page=1#pid20282 ).

I would like to try to have the OPI win working on a 1024 x 768 60 screen. I'm newbie for these things of making custom OS and firmware, so I have no idea if it's possible and no much complicated. 

Do you know if it's not too much complicated to add a new resolution (ie : is it just to add in a special file the new resolution ?) ? If yes could you give me advice or links about the process ? (ie : change the file named X, which is in the path YYYY, test it, and if it works, share this on this Z link to participate) ?

Thanks a lot

**Comment by avafinger** [comment]
I have read you use HDMI to VGA converter, and there is no equivalent resolution on HDMI and your converter fails to do the job. 1024 x 768 is XVGA resolution (4:3) while the current HDMI resolution for the Opi Win Image is 1920 x 1080 (16:9). You could try to lower the HDMI resolution from 1920x1080 to 1280x720@50Hz and see if your converter can do the job.

I am not sure this resolution can be added o the HDMI driver and if it is possible is not an easy task,
@jernejsk is one of the HDMI developers on mainline kernel, maybe he can comment about this resolution.

The current a64-2GB.dtb is set to 1920x1080@60Hz , attached is a DTB for 720p@50Hz, make a backup of your current a64-2GB.dtb and overwrite with the attached one and see if it works.

Make sure you **sync** before you boot with this new configuration. You can always **ssh** to the board, you can use this https://github.com/avafinger/showmyarm (WIP) to know the IP or use a TTL debug or check your Wifi router.

**Comment by avafinger** [comment]
ops, now attached...
[a64-2GB_720p@50Hz.dtb.zip](https://github.com/avafinger/opi-win-a64-firmware/files/1211360/a64-2GB_720p.50Hz.dtb.zip)

**Comment by openelearning** [comment]
Thanks a lot for your attention and reply.
You told me "You could try to lower the HDMI resolution from 1920x1080 to 1280x720@50Hz" this is could be done by using the dtb file only or there is also other ways to do this ?
Thanks i will try to ask to @jernejsk.
I don't know if this information is important but with the same screens (1024 x 768 & the other screen where you distrib was displayed 1280x1024) and the same HDMI to VGA cable the raspberry pi displayed well on both screens with an customized raspbian (PrimTux.org).
I changed with my debian 8.9 on my laptop the a64-2GB.dtb : i put the sd card, ctrl+c, ctrl + v, open a terminal, sync, and put the sdcard on the orange pi. On 1024 x 768 screen was displayed "impossible to display" and on 1280x1024 screen was displayed " Cannot display this video mode. Optimum resolution 1280 x 1024 60Hz". I'm very happy to know that boot/a64/a64-2GB.dtb seems to be the key of the problem. I have also seen that yoctoproject.org could make this kind of  file.

I have also found this thread a bout the subject : https://forum.pine64.org/archive/index.php?thread-158.html

Be able to have a kiss solution for the Orange Pi Win with VGA is important because the goal of this project is to deploy GNU/Linux in school and make reuse of old screen in KISS and low cost way, for doing Makers things for children. It seems that there is 3 ways : find an other openharware nanocomputer with drivers that can run on a lot of screen, find a good and cheap HDMI to VGA that can convert (but tillim said "You can purchase scaling type HDMi to VGA adapter but the price is much higher" in https://forum.pine64.org/archive/index.php?thread-158.html), and the last way is try to contribute to improve this with orange pi win +, but i'm newbie in this things (but i'm interested in learning about it) and you said that's not an easy task if it's possible. There is maybe an other way, the C.H.i.P ways that provide an VGA adapter without using HDMI (https://getchip.com/pages/chip )and that works for me, C.H.I.P was ok on both screen. It seems that the best option for the moment is asking that to @jernejsk.

Thanks a lot for your help and your quick reply :)

**Comment by avafinger** [comment]
Yes the DTB stands for Device Tree Blob where the u-boot and kernel gets
some configurations about the board, HDMI for instance.

I have set HDMI to 50Hz maybe this explain "cannot display video... 60 Hz",
we have one last try adjusting it to 60 Hz, give some minutes and try with
new dtb file....

**Comment by avafinger** [comment]
Try this dtb file (60 Hz) and see if it works or just change the message
error.
If this does not work sounds like your HDMI to VGA adapter can't scale the
image and the only solution is to implement this resolution as Rpi does.

**Comment by openelearning** [comment]
Many thanks. It seems that the file isn't attached ?

**Comment by avafinger** [comment]
Sorry, attached.
[a64-2GB_720p@60Hz.dtb.zip](https://github.com/avafinger/opi-win-a64-firmware/files/1214604/a64-2GB_720p.60Hz.dtb.zip)

**Comment by openelearning** [comment]
![p1410056](https://user-images.githubusercontent.com/24316130/29169196-ff10a0c0-7dd2-11e7-9d2f-e42b28fc0945.JPG)
![p1410057](https://user-images.githubusercontent.com/24316130/29169195-ff0e0db0-7dd2-11e7-8de0-2b589d472d9a.JPG)

Thanks, it works on both screen !

**Comment by avafinger** [comment]
Nice it works! We know know it works with 1024 x 768. Good Luck with you
project and Spread the News... Please close the issue

**Comment by openelearning** [comment]
Thanks, I will tell it about on the orange pi forum. Could you tell please tell me how did you do this dtb file ? (yoctoproject, using armbian github files, using orangepi github https://github.com/orangepi-xunlong ... ?)
