### ISSUE TITLE
How to build firmware from scratch ?

### ISSUE THREAD

**Issue by nouatzi** [avafinger/opi-win-a64-firmware#3]
Hi, I would like to know how did you build the firmware from scratch ?
Did you follow [orange pi doc](http://www.orangepi.org/Docs/Building.html) ?
Especially I want to connect to a HDMI 5 inch 800x480, but I cannot use your image because it's for 1920x1080
Thank you.

**Comment by avafinger** [comment]
Please, try to follow this instructions: https://github.com/avafinger/opi-win-a64-firmware/issues/1

**Comment by avafinger** [comment]
Can you point which HDMI 5" device you are trying to display?

**Comment by avafinger** [comment]
Please, overwrite a64-2GB.dtb with this 480p attache and see if it works.
[a64-2GB.dtb_480p.zip](https://github.com/avafinger/opi-win-a64-firmware/files/1239864/a64-2GB.dtb_480p.zip)

**Comment by nouatzi** [comment]
Ok, I'm trying to use [this panel](https://www.aliexpress.com/item/Hot-Sale-5-Inch-LCD-HDMI-Display-Monitor-HD-800x480-TFT-LCD-Panel-Module-for-Raspberry/32732615315.html).
I will try your file, and I will tell you if it works.
Thank you very much.

**Comment by avafinger** [comment]
No feedback from user, so i assume it worked.
